=== Mikbac/Engineering-studies/XML/zad2/wyciag-426080.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Wyciag">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Naglowek">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="KodFormularza">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="xs:string" name="kodSystemowy"/>
                      <xs:attribute type="xs:string" name="wersjaSchemy"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element type="xs:byte" name="WariantFormularza"/>
              <xs:element type="xs:byte" name="CelZlozenia"/>
              <xs:element type="xs:dateTime" name="DataWytworzeniaJPK"/>
              <xs:element type="xs:date" name="DataOd"/>
              <xs:element type="xs:date" name="DataDo"/>
              <xs:element type="xs:string" name="DomyslnyKodWaluty"/>
              <xs:element type="xs:short" name="KodUrzedu"/>
              <xs:element name="Bank">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="NazwaBanku"/>
                    <xs:element type="xs:string" name="AdresBanku"/>
                    <xs:element type="xs:string" name="StronaInternetowa"/>
                    <xs:element type="xs:int" name="Infolinia"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="Saldo">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:float" name="SaldoPoczatkowe"/>
                    <xs:element type="xs:float" name="SaldoKoncowe"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Podmiot">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:integer" name="NumerRachunku"/>
              <xs:element type="xs:string" name="NumerIBAN"/>
              <xs:element type="xs:string" name="RodzajRachunku"/>
              <xs:element type="xs:string" name="WalutaRachunku"/>
              <xs:element name="IdentyfikatorPodmiotu">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="Imie"/>
                    <xs:element type="xs:string" name="Nazwisko"/>
                    <xs:element type="xs:string" name="DataUrodzenia"/>
                    <xs:element type="xs:long" name="Pesel"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="AdresPodmiotu">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="KodKraju"/>
                    <xs:element type="xs:string" name="Wojewodztwo"/>
                    <xs:element type="xs:string" name="Powiat"/>
                    <xs:element type="xs:string" name="Gmina"/>
                    <xs:element type="xs:string" name="Ulica"/>
                    <xs:element type="xs:byte" name="NrDomu"/>
                    <xs:element type="xs:byte" name="NrLokalu"/>
                    <xs:element type="xs:string" name="Miejscowosc"/>
                    <xs:element type="xs:string" name="KodPocztowy"/>
                    <xs:element type="xs:string" name="Poczta"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Operacje">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Operacja" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:date" name="DataOperacji"/>
                    <xs:element type="xs:string" name="GodzinaOperacji"/>
                    <xs:element type="xs:date" name="DataWaluty"/>
                    <xs:element type="xs:string" name="TypPlatnosci"/>
                    <xs:element type="xs:string" name="Waluta"/>
                    <xs:element name="OpisOperacji">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element type="xs:string" name="NazwaPodmiotu"/>
                          <xs:element type="xs:integer" name="NrRachunkuPrzeciwstawnego"/>
                          <xs:element type="xs:string" name="DaneAdresowe"/>
                          <xs:element type="xs:string" name="Tytul"/>
                          <xs:element type="xs:string" name="TypOperacji"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element type="xs:float" name="KwotaOperacji"/>
                    <xs:element type="xs:float" name="Saldo"/>
                  </xs:sequence>
                  <xs:attribute type="xs:string" name="IdentyfikatorOperacji" use="optional"/>
                  <xs:attribute type="xs:byte" name="id" use="optional"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="WyciagCtrl">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:byte" name="LiczbaOperacji"/>
              <xs:element type="xs:float" name="SumaObciazen"/>
              <xs:element type="xs:float" name="SumaUznan"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Mikbac/Engineering-studies/XML/zad2/wyciag-426080-z-validacjami.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE Wyciag [
<!ELEMENT KodFormularza (#PCDATA)>
<!ATTLIST KodFormularza 
	kodSystemowy CDATA #REQUIRED
	wersjaSchemy CDATA #REQUIRED>
<!ELEMENT WariantFormularza (#PCDATA)>
<!ELEMENT CelZlozenia (#PCDATA)>
<!ELEMENT DataWytworzeniaJPK (#PCDATA)>
<!ELEMENT DataOd (#PCDATA)>
<!ELEMENT DataDo (#PCDATA)>
<!ELEMENT DomyslnyKodWaluty (#PCDATA)>
<!ELEMENT KodUrzedu (#PCDATA)>
<!ELEMENT NazwaBanku (#PCDATA)>
<!ELEMENT AdresBanku (#PCDATA)>
<!ELEMENT StronaInternetowa (#PCDATA)>
<!ELEMENT Infolinia (#PCDATA)>
<!ELEMENT Bank (NazwaBanku,AdresBanku,StronaInternetowa,Infolinia)>
<!ELEMENT SaldoPoczatkowe (#PCDATA)>
<!ELEMENT SaldoKoncowe (#PCDATA)>
<!ELEMENT Naglowek (KodFormularza,WariantFormularza,CelZlozenia,DataWytworzeniaJPK,DataOd,DataDo,DomyslnyKodWaluty,KodUrzedu,Bank,Saldo)>
<!ELEMENT NumerRachunku (#PCDATA)>
<!ELEMENT NumerIBAN (#PCDATA)>
<!ELEMENT RodzajRachunku (#PCDATA)>
<!ELEMENT WalutaRachunku (#PCDATA)>
<!ELEMENT Imie (#PCDATA)>
<!ELEMENT Nazwisko (#PCDATA)>
<!ELEMENT DataUrodzenia (#PCDATA)>
<!ELEMENT Pesel (#PCDATA)>
<!ELEMENT IdentyfikatorPodmiotu (Imie,Nazwisko,DataUrodzenia,Pesel)>
<!ELEMENT KodKraju (#PCDATA)>
<!ELEMENT Wojewodztwo (#PCDATA)>
<!ELEMENT Powiat (#PCDATA)>
<!ELEMENT Gmina (#PCDATA)>
<!ELEMENT Ulica (#PCDATA)>
<!ELEMENT NrDomu (#PCDATA)>
<!ELEMENT NrLokalu (#PCDATA)>
<!ELEMENT Miejscowosc (#PCDATA)>
<!ELEMENT KodPocztowy (#PCDATA)>
<!ELEMENT Poczta (#PCDATA)>
<!ELEMENT AdresPodmiotu (KodKraju,Wojewodztwo,Powiat,Gmina,Ulica,NrDomu,NrLokalu,Miejscowosc,KodPocztowy,Poczta)>
<!ELEMENT Podmiot (NumerRachunku,NumerIBAN,RodzajRachunku,WalutaRachunku,IdentyfikatorPodmiotu,AdresPodmiotu)>
<!ELEMENT DataOperacji (#PCDATA)>
<!ELEMENT GodzinaOperacji (#PCDATA)>
<!ELEMENT DataWaluty (#PCDATA)>
<!ELEMENT TypPlatnosci (#PCDATA)>
<!ELEMENT Waluta (#PCDATA)>
<!ELEMENT NazwaPodmiotu (#PCDATA)>
<!ELEMENT NrRachunkuPrzeciwstawnego (#PCDATA)>
<!ELEMENT DaneAdresowe (#PCDATA)>
<!ELEMENT Tytul (#PCDATA)>
<!ELEMENT TypOperacji (#PCDATA)>
<!ELEMENT OpisOperacji (NazwaPodmiotu,NrRachunkuPrzeciwstawnego,DaneAdresowe,Tytul,TypOperacji)>
<!ELEMENT KwotaOperacji (#PCDATA)>
<!ELEMENT Saldo (#PCDATA|SaldoPoczatkowe|SaldoKoncowe)*>
<!ELEMENT Operacja (DataOperacji,GodzinaOperacji,DataWaluty,TypPlatnosci,Waluta,OpisOperacji,KwotaOperacji,Saldo)>
<!ATTLIST Operacja 
	IdentyfikatorOperacji CDATA #REQUIRED
	id CDATA #REQUIRED>
<!ELEMENT Operacje (Operacja)+>
<!ELEMENT LiczbaOperacji (#PCDATA)>
<!ELEMENT SumaObciazen (#PCDATA)>
<!ELEMENT SumaUznan (#PCDATA)>
<!ELEMENT WyciagCtrl (LiczbaOperacji,SumaObciazen,SumaUznan)>
<!ELEMENT Wyciag (Naglowek,Podmiot,Operacje,WyciagCtrl)>
]>

<Wyciag xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="wyciag-426080.xsd">
<Naglowek>
	<KodFormularza kodSystemowy="JPK_WB" wersjaSchemy="1-0">JPK_WB</KodFormularza>
	<WariantFormularza>1</WariantFormularza>
	<CelZlozenia>1</CelZlozenia>
	<DataWytworzeniaJPK>2016-07-12T15:24:51</DataWytworzeniaJPK>
	<DataOd>2016-01-01</DataOd>
	<DataDo>2016-06-30</DataDo>
	<DomyslnyKodWaluty>PLN</DomyslnyKodWaluty>
	<KodUrzedu>0402</KodUrzedu>
	<Bank>
		<NazwaBanku>Super Bank</NazwaBanku>
		<AdresBanku>Bagatela 15, 00-585, Warszawa</AdresBanku>
		<StronaInternetowa>superBank.pl</StronaInternetowa>
		<Infolinia>444555444</Infolinia>
	</Bank>
	<Saldo>
		<SaldoPoczatkowe>1000.00</SaldoPoczatkowe>
		<SaldoKoncowe>13700.00</SaldoKoncowe>
	</Saldo>
</Naglowek>
<Podmiot>
	<NumerRachunku>0910205561000050200421818</NumerRachunku>
	<NumerIBAN>PL60370900550454013000224444</NumerIBAN>
	<RodzajRachunku>Super konto</RodzajRachunku>
	<WalutaRachunku>PLN</WalutaRachunku>
	<IdentyfikatorPodmiotu>
		<Imie>Michał</Imie>
		<Nazwisko>Nowak</Nazwisko>
		<DataUrodzenia>04-11-1993</DataUrodzenia>
		<Pesel>9311049457</Pesel>
	</IdentyfikatorPodmiotu>
	<AdresPodmiotu>
		<KodKraju>PL</KodKraju>
		<Wojewodztwo>DOLNOŚLĄSKIE</Wojewodztwo>
		<Powiat>WROCLAW</Powiat>
		<Gmina>WROCLAW</Gmina>
		<Ulica>DOLNA</Ulica>
		<NrDomu>13</NrDomu>
		<NrLokalu>22</NrLokalu>
		<Miejscowosc>WROCLAW</Miejscowosc>
		<KodPocztowy>50-006</KodPocztowy>
		<Poczta>WROCLAW</Poczta>
	</AdresPodmiotu>
</Podmiot>
<Operacje>
	<Operacja IdentyfikatorOperacji="9033FG56432756488" id="1">
		<DataOperacji>2016-01-05</DataOperacji>
		<GodzinaOperacji>13:23</GodzinaOperacji>
		<DataWaluty>2016-01-05</DataWaluty>
		<TypPlatnosci>Wyplata</TypPlatnosci>
		<Waluta>PLN</Waluta>
		<OpisOperacji>
			<NazwaPodmiotu>Bar Kropka sp.z o.o.</NazwaPodmiotu>
			<NrRachunkuPrzeciwstawnego>11237293940000123948201212</NrRachunkuPrzeciwstawnego>
			<DaneAdresowe>ul. Dabrowskiego 25, 22-426, Wroclaw</DaneAdresowe>
			<Tytul>Platnosc</Tytul>
			<TypOperacji>Zakup przy uzyciu karty</TypOperacji>
		</OpisOperacji>
		<KwotaOperacji>-100.00</KwotaOperacji>
		<Saldo>900.00</Saldo>
	</Operacja>
	<Operacja IdentyfikatorOperacji="2343FG21232791488" id="2">
		<DataOperacji>2016-01-25</DataOperacji>
		<GodzinaOperacji>09:37</GodzinaOperacji>
		<DataWaluty>2016-01-25</DataWaluty>
		<TypPlatnosci>Wyplata</TypPlatnosci>
		<Waluta>PLN</Waluta>
		<OpisOperacji>
			<NazwaPodmiotu>Witchen</NazwaPodmiotu>
			<NrRachunkuPrzeciwstawnego>83958323940000123948201212</NrRachunkuPrzeciwstawnego>
			<DaneAdresowe>ul. Dmowskiego 80, 22-426, Warszawa</DaneAdresowe>
			<Tytul>Wplata</Tytul>
			<TypOperacji>Zakup przy uzyciu karty</TypOperacji>
		</OpisOperacji>
		<KwotaOperacji>-500.00</KwotaOperacji>
		<Saldo>400.00</Saldo>
	</Operacja>
	<Operacja IdentyfikatorOperacji="123FG21232654488" id="3">
		<DataOperacji>2016-01-31</DataOperacji>
		<GodzinaOperacji>16:45</GodzinaOperacji>
		<DataWaluty>2016-01-31</DataWaluty>
		<TypPlatnosci>Wplata</TypPlatnosci>
		<Waluta>PLN</Waluta>
		<OpisOperacji>
			<NazwaPodmiotu>QB Co.</NazwaPodmiotu>
			<NrRachunkuPrzeciwstawnego>11201456940342123948201212</NrRachunkuPrzeciwstawnego>
			<DaneAdresowe>ul. Fryderyka Chopina 5, 22-426, Warszawa</DaneAdresowe>
			<Tytul>Pensja</Tytul>
			<TypOperacji>Przelew</TypOperacji>
		</OpisOperacji>
		<KwotaOperacji>3500.00</KwotaOperacji>
		<Saldo>3900.00</Saldo>
	</Operacja>
	<Operacja IdentyfikatorOperacji="3453FG25675791488" id="4">
		<DataOperacji>2016-02-21</DataOperacji>
		<GodzinaOperacji>08:56</GodzinaOperacji>
		<DataWaluty>2016-02-21</DataWaluty>
		<TypPlatnosci>Wyplata</TypPlatnosci>
		<Waluta>PLN</Waluta>
		<OpisOperacji>
			<NazwaPodmiotu>LokDom sp. z o. o.</NazwaPodmiotu>
			<NrRachunkuPrzeciwstawnego>94857323940000123948201212</NrRachunkuPrzeciwstawnego>
			<DaneAdresowe>ul. Kazimierza Wielkiego 11, 22-426, Wroclaw</DaneAdresowe>
			<Tytul>Oplata za mieszkanie</Tytul>
			<TypOperacji>Przelew</TypOperacji>
		</OpisOperacji>
		<KwotaOperacji>-1500.00</KwotaOperacji>
		<Saldo>2400.00</Saldo>
	</Operacja>
	<Operacja IdentyfikatorOperacji="8763FG21232981488" id="5">
		<DataOperacji>2016-02-29</DataOperacji>
		<GodzinaOperacji>18:32</GodzinaOperacji>
		<DataWaluty>2016-02-29</DataWaluty>
		<TypPlatnosci>Wplata</TypPlatnosci>
		<Waluta>PLN</Waluta>
		<OpisOperacji>
			<NazwaPodmiotu>QB Co.</NazwaPodmiotu>
			<NrRachunkuPrzeciwstawnego>11201456940342123948201212</NrRachunkuPrzeciwstawnego>
			<DaneAdresowe>ul. Fryderyka Chopina 5, 22-426, Warszawa</DaneAdresowe>
			<Tytul>Pensja</Tytul>
			<TypOperacji>Przelew</TypOperacji>
		</OpisOperacji>
		<KwotaOperacji>3500.00</KwotaOperacji>
		<Saldo>5900.00</Saldo>
	</Operacja>
	<Operacja IdentyfikatorOperacji="4683FG21237651488" id="6">
		<DataOperacji>2016-03-03</DataOperacji>
		<GodzinaOperacji>15:08</GodzinaOperacji>
		<DataWaluty>2016-03-03</DataWaluty>
		<TypPlatnosci>Wyplata</TypPlatnosci>
		<Waluta>PLN</Waluta>
		<OpisOperacji>
			<NazwaPodmiotu>Bar Kropka sp.z o.o.</NazwaPodmiotu>
			<NrRachunkuPrzeciwstawnego>11237293940000123948201212</NrRachunkuPrzeciwstawnego>
			<DaneAdresowe>ul. Dabrowskiego 25, 22-426, Wroclaw</DaneAdresowe>
			<Tytul>Platnosc</Tytul>
			<TypOperacji>Zakup przy uzyciu karty</TypOperacji>
		</OpisOperacji>
		<KwotaOperacji>-100.00</KwotaOperacji>
		<Saldo>5800.00</Saldo>
	</Operacja>
	<Operacja IdentyfikatorOperacji="6543FG21237651488" id="7">
		<DataOperacji>2016-03-11</DataOperacji>
		<GodzinaOperacji>14:52</GodzinaOperacji>
		<DataWaluty>2016-03-11</DataWaluty>
		<TypPlatnosci>Wplata</TypPlatnosci>
		<Waluta>PLN</Waluta>
		<OpisOperacji>
			<NazwaPodmiotu>LokDom sp. z o. o.</NazwaPodmiotu>
			<NrRachunkuPrzeciwstawnego>94857323940000123948201212</NrRachunkuPrzeciwstawnego>
			<DaneAdresowe>ul. Kazimierza Wielkiego 11, 22-426, Wroclaw</DaneAdresowe>
			<Tytul>Oplata za mieszkanie</Tytul>
			<TypOperacji>Przelew</TypOperacji>
		</OpisOperacji>
		<KwotaOperacji>-1500.00</KwotaOperacji>
		<Saldo>4300.00</Saldo>
	</Operacja>
	<Operacja IdentyfikatorOperacji="8763FG21232765488" id="8">
		<DataOperacji>2016-03-31</DataOperacji>
		<GodzinaOperacji>06:59</GodzinaOperacji>
		<DataWaluty>2016-03-31</DataWaluty>
		<TypPlatnosci>Wplata</TypPlatnosci>
		<Waluta>PLN</Waluta>
		<OpisOperacji>
			<NazwaPodmiotu>QB Co.</NazwaPodmiotu>
			<NrRachunkuPrzeciwstawnego>11201456940342123948201212</NrRachunkuPrzeciwstawnego>
			<DaneAdresowe>ul. Fryderyka Chopina 5, 22-426, Warszawa</DaneAdresowe>
			<Tytul>Pensja</Tytul>
			<TypOperacji>Przelew</TypOperacji>
		</OpisOperacji>
		<KwotaOperacji>3500.00</KwotaOperacji>
		<Saldo>7800.00</Saldo>
	</Operacja>
	<Operacja IdentyfikatorOperacji="2353FG21236541488" id="9">
		<DataOperacji>2016-04-03</DataOperacji>
		<GodzinaOperacji>11:22</GodzinaOperacji>
		<DataWaluty>2016-04-03</DataWaluty>
		<TypPlatnosci>Wyplata</TypPlatnosci>
		<Waluta>PLN</Waluta>
		<OpisOperacji>
			<NazwaPodmiotu>LokDom sp. z o. o.</NazwaPodmiotu>
			<NrRachunkuPrzeciwstawnego>94857323940000123948201212</NrRachunkuPrzeciwstawnego>
			<DaneAdresowe>ul. Kazimierza Wielkiego 11, 22-426, Wroclaw</DaneAdresowe>
			<Tytul>Oplata za mieszkanie</Tytul>
			<TypOperacji>Przelew</TypOperacji>
		</OpisOperacji>
		<KwotaOperacji>-1500.00</KwotaOperacji>
		<Saldo>6300.00</Saldo>
	</Operacja>
	<Operacja IdentyfikatorOperacji="3543FG21232467488" id="10">
